# Generated by Django 4.1.13 on 2025-04-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nazareth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
