# Generated by Django 4.1.13 on 2025-04-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nazareth', '0002_patient_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='temp_password',
        ),
    ]
