# Generated by Django 4.1.13 on 2025-04-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nazareth', '0004_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
